# Generated by Django 3.1 on 2021-06-09 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BooksForFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Обложка')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_for_free', to='books.category', verbose_name='Категория')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_for_free', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Книга бесплатная',
                'verbose_name_plural': 'Книги бесплатные',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BooksForBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Обложка')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('finish_goal', models.PositiveIntegerField(verbose_name='Цель')),
                ('current_goal', models.PositiveIntegerField(default=0, verbose_name='Собрано')),
                ('end', models.BooleanField(default=False, verbose_name='Сбор окончен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyers', models.ManyToManyField(related_name='books_for_buy', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_for_buy', to='books.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Книга для покупки',
                'verbose_name_plural': 'Книги для покупок',
                'ordering': ['-id'],
            },
        ),
    ]
