# Generated by Django 3.1 on 2021-06-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210609_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksforfree',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
