# Generated by Django 3.1 on 2021-06-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210609_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksforbuy',
            name='book_url',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
    ]
