# Generated by Django 3.1 on 2021-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_booksforbuy_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksforfree',
            name='book_file',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d/', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='booksforfree',
            name='book_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
