# Generated by Django 3.1 on 2021-06-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210612_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksforfree',
            name='book_url',
        ),
    ]
