# Generated by Django 3.1 on 2021-06-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20210614_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст'),
        ),
    ]
