# Generated by Django 3.1 on 2021-06-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20210609_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг пользователя'),
        ),
    ]
